Vagrant.configure("2") do |config|
  # Escolhe a box do Debian 12
  config.vm.box = "generic/debian12"

  # Define hostname
  config.vm.hostname = "debian-webserver"

  # Configurações de rede
  config.vm.network "private_network", ip: "192.168.56.20"

  # Provisionamento com shell script
  #config.vm.provision "shell", inline: <<-SHELL
   
  #SHELL
end
